[package]
name = "the_prime_idle"
version = "0.8.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
primes = "0.3.0"
catch-input = "1.1.2"